name: "Prime Theme Tokens Generator"
label: "Generate Theme Tokens"
description: "Generates theme tokens for Prime users based on their public key."
inputs:
  public-key:
    type: "string"
    description: "Public key for authentication"
    required: true
  tokens-path:
    type: "string"
    default: "./tokens.json"
    description: "Path to the tokens file"
  output-dir:
    type: "string"
    default: "./"
    description: "Path to the output directory"
runs:
  using: "node16"
  main: "dist/index.js"

