name: PrimeTokens

on:
    push:
        paths:
            - 'tokens.json'

permissions:
    contents: write

jobs:
    generate-tokens:
        name: Generate Prime Tokens
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Generate Prime Tokens
              uses: mertsincan/primetokens@main
              with:
                PUBLIC_KEY: ${{ secrets.PRIME_TOKEN_PUBLIC_KEY }}   # required public key for authentication
                TOKENS_PATH: 'tokens.json'                          # default path
                OUTPUT_DIR: './'                                    # default output directory