name: PrimeTokens

on:
    push:
        paths:
            - 'tokens.json'

permissions:
    contents: write

jobs:
    generate-tokens:
        name: Generate Prime Tokens
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Generate Prime Tokens
              uses: mertsincan/primetokens@main
              with:
                api-key: ${{ secrets.PRIME_TOKEN_PUBLIC_KEY }}   # [required] api key for authentication
                tokens-path: 'tokens.json'                       # [optional] path to tokens file
                output-dir: './'                                 # [optional] output directory